buildscript {
    repositories {
        maven { url = "https://maven.minecraftforge.net" }
        maven { url = "https://www.cursemaven.com" }
        mavenCentral()
    }

    dependencies {
        minecraft "net.minecraftforge:forge:1.12.2-14.23.5.2864"

        implementation fg.deobf("curse.maven:botania-225643:3337685")
    }
}

apply plugin: "net.minecraftforge.gradle"
apply plugin: "eclipse"
apply plugin: "idea"

version = "1.5.4"
group = "com.bartz24.voidislandcontrol"
archivesBaseName = "voidislandcontrol"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = "1.8"

minecraft {
    mappings channel: "stable", version: "39-1.12"

    runs {
        client {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
        }
        server {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
        }
    }
}

repositories {
    maven { url = "https://maven.minecraftforge.net" }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:1.12.2-14.23.5.2864"

    // local Botania deobf jar you already have
    implementation files("lib/Botania r1.10-354-deobf.jar")
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "voidislandcontrol",
                "Specification-Vendor"    : "bartz24",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version,
                "Implementation-Vendor"   : "bartz24",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

processResources {
    inputs.property "version", project.version
    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"
        expand "version": project.version, "mcversion": "1.12.2"
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}